### ISSUE TITLE
Must the mutex name be unique?

### ISSUE THREAD

**Issue by fabtopia** [Tools4everBV/HelloID-Conn-Prov-Target-CSV#1]
A need two of the provision target connectors. I think i have to make the Mutexname unique for every connector. Is that right or can it be de the same?

**Comment by rschouten97** [comment]
IMO we should rework this connector.
Since we have concurrent sessions now, we have no need for the mutex anymore.
With concurrent actions we can make sure only one action opens the file (as long as it is one file per connector).
